### ISSUE TITLE
help on commands

### ISSUE THREAD

**Issue by jjsilva33** [gitaeuber/axpert#1]
Hello Friend!
congratulations on the project. could you give examples of how to use your shell to get information from the inverter?

**Comment by gitaeuber** [comment]
Hi Jefferson,

you need to change the $DEV variable in the script to your needs e.g.
DEV=/dev/ttyUSB2
I use my script over TCP/IP with connection to a ser2net server only. So I don't know if it works via /dev/ttyUSB_ directly. It should.

Then just use commands to ask the inverter to tell you the requested values.
example:
bash$ ~/src/axpert/axpert.sh QPIRI
QPIRI	230.0 21.7 230.0 50.0 21.7 5000 5000 48.0 48.0 47.6 52.5 50.3 2 02 120 1 2 1 9 01 0 0 50.0 1 1 015

Attached is a list of commands.

Cheers,
Lars


On Sat, 30 May 2020 21:12:43 -0700
Jefferson <notifications@github.com> wrote:

> Hello Friend!
> congratulations on the project. could you give examples of how to use your shell to get information from the inverter?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gitaeuber/axpert/issues/1


-- 
Schöne Grüße
Lars Täuber

**Comment by jjsilva33** [comment]
Get it, Lars!
What other tool do you use to view the information generated by the inverter?

Cheers,
Jefferson

**Comment by gitaeuber** [comment]
I import text files into influx and visualize with grafana.

Cheers,
Lars

**Comment by jjsilva33** [comment]
hello Lars!
the file generated in log_axpert.sh is ready to import to influxdb? or does it have to be treated in the file so that I can import?

Cheers,
Jefferson

**Comment by gitaeuber** [comment]
Hello Jefferson,

no the generated output is meant as a logfile. I gzip them at the end of the month and then archive all files at the end of the year. If something goes wrong with influx I have "human readable" (csv like) backups.
It happend that I switched from an older visualization system to influx & grafana. So I only adopted my scripts an imported all data from the archived files.

I have an awk script (cronjob) that produces output for influx:

tail -10 "$LOG_FILE" \
| axpert2influx.awk 2>/dev/null \
| curl -s -i -XPOST 'http://localhost:8086/write?db=XXX' --data-binary @-

The axpert2influx.awk is attached. It imports not all values but only the ones I'd like to be presented.

Cheers,
Lars



On Wed, 03 Jun 2020 07:58:21 -0700
Jefferson <notifications@github.com> wrote:

> hello Lars!
> the file generated in log_axpert.sh is ready to import to influxdb? or does it have to be treated in the file so that I can import?
> 
> Cheers,
> Jefferson
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/gitaeuber/axpert/issues/1#issuecomment-638253526


-- 
Schöne Grüße
Lars Täuber

**Comment by jjsilva33** [comment]
Hello Lars,
I swear I tried to understand how importing to influxdb works with awk, but I didn't understand. how to send the script to my email?
my email is: jefferson.joaquim@gmail.com

Cheers, 
Jefferson
